# Generated by Django 6.0.3 on 2026-04-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(default='Unknown', max_length=300)),
                ('rating', models.FloatField(default=0.0)),
                ('reviews_count', models.IntegerField(default=0)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('book_url', models.URLField(max_length=1000, unique=True)),
                ('cover_image_url', models.URLField(blank=True, max_length=1000)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_genre', models.CharField(blank=True, max_length=200)),
                ('sentiment', models.CharField(blank=True, max_length=100)),
                ('is_embedded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('sources', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
